# Generated by Django 2.0.3 on 2018-06-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='photo.Tag'),
        ),
    ]
