# Generated by Django 2.0.3 on 2018-04-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='char_tag',
            field=models.CharField(blank=True, max_length=240),
        ),
        migrations.AlterField(
            model_name='tag',
            name='int_tag',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='time_tag',
            field=models.TimeField(blank=True),
        ),
    ]
