# Generated by Django 2.0.3 on 2018-05-30 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='char_tag',
            new_name='char',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='int_tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='time_tag',
        ),
    ]
