# Generated by Django 2.0.3 on 2018-05-30 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20180530_2357'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='char',
            new_name='tag',
        ),
    ]
